# Generated by Django 5.0.2 on 2024-03-14 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='thmb_image',
            new_name='thumb_image',
        ),
    ]
